version: '3'
services:
  localstack:
    image: localstack/localstack:0.11.2
    container_name: localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8888}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./aws:/docker-entrypoint-initaws.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      bfb:
        ipv4_address: 174.101.101.102

networks:
  bfb:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.101.101.0/24